-- WareWise PostgreSQL schema.

BEGIN;

CREATE TABLE IF NOT EXISTS warehouse (
    warehouse_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    address text
);

CREATE TABLE IF NOT EXISTS categories (
    category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name text NOT NULL,
    contact_email text UNIQUE,
    contact_phone text,
    address text,
    created_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    email text UNIQUE,
    created_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text,
    role text NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'WORKER'))
);

CREATE TABLE IF NOT EXISTS user_warehouses (
    user_id integer NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    warehouse_id integer NOT NULL REFERENCES warehouse(warehouse_id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (user_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS items_general_data (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    set_quantity integer NOT NULL DEFAULT 0,
    barcode varchar(255),
    category_id integer REFERENCES categories(category_id) ON UPDATE CASCADE ON DELETE SET NULL,
    supplier_id integer REFERENCES suppliers(supplier_id) ON UPDATE CASCADE ON DELETE SET NULL,
    price integer NOT NULL DEFAULT 0,
    expires boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS inventory (
    inventory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    stock_quantity integer NOT NULL DEFAULT 0,
    description text,
    last_updated varchar(255) DEFAULT CURRENT_TIMESTAMP::text,
    warehouse_id integer REFERENCES warehouse(warehouse_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    general_item_id integer REFERENCES items_general_data(id) ON UPDATE CASCADE ON DELETE SET NULL,
    status text NOT NULL CHECK (status IN ('PENDING', 'FULFILLED', 'CANCELLED')),
    created_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text,
    updated_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text,
    user_id integer REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    quantity integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer REFERENCES orders(order_id) ON UPDATE CASCADE ON DELETE SET NULL,
    inventory_id integer REFERENCES inventory(inventory_id) ON UPDATE CASCADE ON DELETE SET NULL,
    quantity integer NOT NULL DEFAULT 0,
    general_item_id integer REFERENCES items_general_data(id) ON UPDATE CASCADE ON DELETE SET NULL,
    expire_date varchar(255),
    sold boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS stock_alerts (
    stock_alert_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer REFERENCES inventory(inventory_id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text,
    resolved boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS logs (
    log_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text,
    action text NOT NULL,
    description text,
    created_at varchar(255) DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE IF NOT EXISTS forgot_password_table (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    token varchar(2048) NOT NULL UNIQUE,
    expiration_date varchar(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_items_inventory_id ON items(inventory_id);
CREATE INDEX IF NOT EXISTS idx_items_general_item_id ON items(general_item_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_general_item_id ON orders(general_item_id);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_product_id ON stock_alerts(product_id);
CREATE INDEX IF NOT EXISTS idx_forgot_password_table_user_id ON forgot_password_table(user_id);
CREATE INDEX IF NOT EXISTS idx_logs_username ON logs(username);
CREATE INDEX IF NOT EXISTS idx_user_warehouses_user_id ON user_warehouses(user_id);
CREATE INDEX IF NOT EXISTS idx_user_warehouses_warehouse_id ON user_warehouses(warehouse_id);

CREATE OR REPLACE FUNCTION refresh_inventory_stock()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE inventory inv
    SET
        stock_quantity = COALESCE(stock.total_quantity, 0),
        last_updated = CURRENT_TIMESTAMP::text
    FROM (
        SELECT inventory_id, SUM(quantity) AS total_quantity
        FROM items
        WHERE sold = false AND inventory_id IS NOT NULL
        GROUP BY inventory_id
    ) stock
    WHERE inv.inventory_id = stock.inventory_id;

    UPDATE inventory inv
    SET
        stock_quantity = 0,
        last_updated = CURRENT_TIMESTAMP::text
    WHERE NOT EXISTS (
        SELECT 1
        FROM items item
        WHERE item.inventory_id = inv.inventory_id
          AND item.sold = false
    );
END;
$$;

COMMIT;
